development:
  clients:
    default:
      database: androidbugsolver_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: androidbugsolver_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
       connect_timeout: 15
